owner: center-for-applied-ocean-technology
repo: smartatlantic-monitor
sites:
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: SmartAtlantic
  url: https://www.smartatlantic.ca
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: SmartAtlantic ERDDAP
  url: https://www.smartatlantic.ca/erddap/index.html
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Channel-Port Aux Basques Buoy
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_port_aux_basques.json?time&time>=now-240minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Channel-Port Aux Basques Tide Station
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_port_aux_basqes_wharf.json?time&time>=now-20minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: COVE Weather Station, IDARTM1
  url: https://www.smartatlantic.ca/erddap/tabledap/cove_weather_station_idartm1.json?time&time>=now-30min&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Diamond Jubilee Cruise Ship Terminal Meteorological Station
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_saint_john_cruise_terminal.json?time&time>=now-20minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: ECCC OPP, 44488, East Chedabucto Bay
  url: https://www.smartatlantic.ca/erddap/tabledap/eccc_opp_44488_east_chedabucto_bay.json?time&time>=now-20minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: ECCC OPP, 44489, West Chedabucto Bay
  url: https://www.smartatlantic.ca/erddap/tabledap/eccc_opp_44489_west_chedabucto_bay.json?time&time>=now-20minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: ECCC OPP, 44490, West Bay of Fundy
  url: https://www.smartatlantic.ca/erddap/tabledap/eccc_opp_44490_west_bay_of_fundy.json?time&time>=now-20minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Fortune Bay Buoy
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_Fortune_Bay_Buoy.json?time&time>=now-120minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: 'Fortune Bay: Dog Island - DOGIS'
  url: https://www.smartatlantic.ca/erddap/tabledap/DFO_Sutron_DOGIS.json?time&time>=now-2hours&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: 'Fortune Bay: Pool''s Cove - POOLC'
  url: https://www.smartatlantic.ca/erddap/tabledap/DFO_Sutron_POOLC.json?time&time>=now-2hours&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Halifax (Herring Cove) Buoy
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_halifax.json?time&time>=now-60minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: 'Halifax Ocean Terminals: Fairview'
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_halifax_fairview.json?time&time>=now-20minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: 'Halifax Ocean Terminals: Pier 31'
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_halifax_anemometer1.json?time&time>=now-20minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: 'Halifax Ocean Terminals: Pier 9C'
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_halifax_pier9c.json?time&time>=now-20minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Holyrood Buoy 1, Raw Wind Data
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_Holyrood_Buoy1_wind_raw.json?time&time>=now-10min&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Holyrood Buoy 2
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_Holyrood_Buoy2.json?time&time>=now-120minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Holyrood Shore Station, Test
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_holyrood_shore_station.json?time&time>=now-10min&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Holyrood Wharf Weather Station
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_holyrood_wharf.json?time&time>=now-44minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Mouth of Placentia Bay Buoy
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_MouthofPlacentiaBayBuoy.json?time&time>=now-60minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: MSC Datamart realtime moored buoy data
  url: https://www.smartatlantic.ca/erddap/tabledap/eccc_opp_atlantic.json?time&time>=now-20minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: NEGL, Black Tickle-Domino, NunatuKavut (NLQU0003)
  url: https://www.smartatlantic.ca/erddap/tabledap/sma_negl_black_tickle_nlqu0003.json?time&time>=now-2hours&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: NEGL, Cartwright Junction, Labrador (NLQU0004)
  url: https://www.smartatlantic.ca/erddap/tabledap/sma_negl_cartwright_junction_nlqu0004.json?time&time>=now-2hours&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: NEGL, North West River, Labrador (NLQU0007)
  url: https://www.smartatlantic.ca/erddap/tabledap/sma_negl_north_west_river_nlqu0007.json?time&time>=now-2hours&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: NEGL, Postville, Nunatsiavut (NLQU0001)
  url: https://www.smartatlantic.ca/erddap/tabledap/sma_negl_postville_nlqu0001.json?time&time>=now-2hours&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: NEGL, Red Bay, NunatuKavut (NLQU0005)
  url: https://www.smartatlantic.ca/erddap/tabledap/sma_negl_red_bay_nlqu0005.json?time&time>=now-2hours&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: NEGL, Rigolet, Nunatsiavut (NLQU0002)
  url: https://www.smartatlantic.ca/erddap/tabledap/sma_negl_rigolet_nlqu0002.json?time&time>=now-2hours&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Pilot Boarding Station / Red Island Shoal Buoy
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_red_island_shoal.json?time&time>=now-8hours&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: 'Placentia Bay: North Harbour - NHARB'
  url: https://www.smartatlantic.ca/erddap/tabledap/DFO_Sutron_NHARB.json?time&time>=now-2hours&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: 'Placentia Bay: Ragged Islands - KLUMI'
  url: https://www.smartatlantic.ca/erddap/tabledap/DFO_Sutron_KLUMI.json?time&time>=now-2hours&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Saint John Buoy
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_saint_john.json?time&time>=now-60minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: Shipissipan, Remote Automatic Weather Station (RAWS), Nitassinan
  url: https://www.smartatlantic.ca/erddap/tabledap/parks_canada_shipissipan.json?time&time>=now-2hour&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: St. John's Buoy
  url: https://www.smartatlantic.ca/erddap/tabledap/SMA_st_johns.json?time&time>=now-120minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: XEOS H1 Buoy Wave Sensor
  url: https://www.smartatlantic.ca/erddap/tabledap/SmartAtlantic_XEOS_h1_buoy.json?time&time>=now-120minutes&distinct()
- assignees:
  - sjbruce
  - RichardJKelly
  maxResponseTime: 5000
  name: XEOS HKB Buoy Wave Sensor
  url: https://www.smartatlantic.ca/erddap/tabledap/SmartAtlantic_XEOS_hkb_buoy.json?time&time>=now-120minutes&distinct()
status-website:
  baseUrl: /smartatlantic-monitor
  introMessage: "This repository monitors the SmartAtlantic ocean observation service and its real-time datasets. It is powered by [**Upptime**](https://github.com/upptime/upptime)."
  introTitle: 'SmartAtlantic website and real-time dataset monitor'
  logoUrl: https://www.smartatlantic.ca/images/SmartAtlantic_Logo_v2_500px.png
  name: Monitor
  navbar:
  - href: /
    title: Status
  - href: https://github.com/$OWNER/$REPO
    title: GitHub
  metaTags:
  - name: "robots"
    content: "noindex"
