owner: center-for-applied-ocean-technology
repo: smartatlantic-monitor
sites:
- assignees:
  - sjbruce
  maxResponseTime: 5000
  name: SmartAtlantic
  url: https://www.smartatlantic.ca
  
- assignees:
  - sjbruce
  maxResponseTime: 5000
  name: SmartAtlantic ERDDAP
  url: https://www.smartatlantic.ca/erddap/index.html

status-website:
  baseUrl: /smartatlantic-monitor
  introMessage: "This repository monitors the SmartAtlantic ocean observation service and its real-time datasets. It is powered by [**Upptime**](https://github.com/upptime/upptime)."
  introTitle: 'SmartAtlantic website and real-time dataset monitor'
  logoUrl: https://www.smartatlantic.ca/images/SmartAtlantic_Logo_v2_500px.png
  name: Monitor
  navbar:
  - href: /
    title: Status
  - href: https://github.com/$OWNER/$REPO
    title: GitHub
  metaTags:
  - name: "robots"
    content: "noindex"
